language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-node-sweetjs' ]; then cd .. && eval "mv $currentfolder generator-node-sweetjs" && cd generator-node-sweetjs; fi
